"""
- The question: we are given a list of heights that tells the height of blocks which all have a width of 1, and tasked to return the maximum area that could be formed from those blocks.
- Solution:
    - this is a hard problem which can be solved using a monotonically increasing stack and some how greedy.
    - we iterate over the heights and when we find  aheight we check our stack and if it is empty we directly add the heights and its index to our stack,
    - but if there is an element in it we compare the element and the height and if the current height is larger than or equal the top element we add it 
    - but if it is less than the top element we pop from our stack until we find a smaller or equal or empty stack.
    - and when we pop from our stack we process the are they could have generated with the current block.
    - we do that for all our height and if after we finish the iteration we check if there is an element in our stack we process it by taking the len of our heights list and its index and check the area of rectangle generated by them.
    - and thats it we return the max.
-  Time and Space complexity:
    - Time = O(n), n = len(heights)
    - space = O(n), 
"""

class Solution:
    def largestRectangleArea(self, heights: List[int]) -> int:
        stack = []
        max_area = 0

        # we iterate over the heights and check the area they generate.
        for idx, height in enumerate(heights):

            # if our stack contains atleast one element and it is less than our current height or equal to it or our stack is empty
            if (stack and stack[-1][1] <= height) or not stack:
                stack.append((idx, height))
            
            # else if the top element is smaller than the current height we pop from our stack and process them
            else:
                while stack and stack[-1][1] > height:
                    temp = stack.pop()
                    area = (idx - temp[0]) * temp[1]
                    max_area = max(max_area, area)

                # we append the current height after processing all the previous heights with less value with index of the last processed element to expand the current element further to back
                stack.append((temp[0], height))

        # we check if there is any element leftto our stack and if so we process them by generating the rectangle with the last block since they expand until the end of our heights list.
        while stack:
            temp = stack.pop()
            area = (len(heights) - temp[0]) * temp[1]
            max_area = max(max_area, area)

        return max_area

            
            

